# Generated by Django 5.2.5 on 2025-08-18 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, help_text='Data do lançamento (apenas um por dia)', unique=True, verbose_name='📅 Data')),
                ('pix', models.DecimalField(decimal_places=2, default=0, help_text='Valor recebido via PIX', max_digits=10, verbose_name='📱 PIX')),
                ('dinheiro', models.DecimalField(decimal_places=2, default=0, help_text='Valor recebido em dinheiro', max_digits=10, verbose_name='💵 Dinheiro')),
                ('cartao', models.DecimalField(decimal_places=2, default=0, help_text='Valor recebido via cartão', max_digits=10, verbose_name='💳 Cartão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': '💰 Lançamento',
                'verbose_name_plural': '💰 Lançamentos',
                'ordering': ['-data'],
            },
        ),
    ]
