# Generated by Django 5.2.5 on 2025-08-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamento',
            name='cartao',
        ),
        migrations.AddField(
            model_name='lancamento',
            name='cartao_credito',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor recebido via cartão de crédito', max_digits=10, verbose_name='🔄 Cartão Crédito'),
        ),
        migrations.AddField(
            model_name='lancamento',
            name='cartao_debito',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor recebido via cartão de débito', max_digits=10, verbose_name='💳 Cartão Débito'),
        ),
    ]
