# Generated by Django 5.2.5 on 2025-08-18 21:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Santander, Nubank, Itaú', max_length=50, verbose_name='Nome do Cartão')),
                ('limite', models.DecimalField(blank=True, decimal_places=2, help_text='Limite do cartão (opcional)', max_digits=10, null=True, verbose_name='Limite')),
                ('vencimento_fatura', models.IntegerField(choices=[(1, 'Dia 1'), (2, 'Dia 2'), (3, 'Dia 3'), (4, 'Dia 4'), (5, 'Dia 5'), (6, 'Dia 6'), (7, 'Dia 7'), (8, 'Dia 8'), (9, 'Dia 9'), (10, 'Dia 10'), (11, 'Dia 11'), (12, 'Dia 12'), (13, 'Dia 13'), (14, 'Dia 14'), (15, 'Dia 15'), (16, 'Dia 16'), (17, 'Dia 17'), (18, 'Dia 18'), (19, 'Dia 19'), (20, 'Dia 20'), (21, 'Dia 21'), (22, 'Dia 22'), (23, 'Dia 23'), (24, 'Dia 24'), (25, 'Dia 25'), (26, 'Dia 26'), (27, 'Dia 27'), (28, 'Dia 28'), (29, 'Dia 29'), (30, 'Dia 30'), (31, 'Dia 31')], default=10, help_text='Dia do mês que vence a fatura', verbose_name='Vencimento da Fatura')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': '💳 Cartão de Crédito',
                'verbose_name_plural': '💳 Cartões de Crédito',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome ou razão social do fornecedor', max_length=100, verbose_name='Nome do Fornecedor')),
                ('contato', models.CharField(blank=True, help_text='Telefone, email ou pessoa de contato', max_length=100, verbose_name='Contato')),
                ('observacoes', models.TextField(blank=True, help_text='Informações adicionais sobre o fornecedor', verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, help_text='Fornecedor ativo para novas compras', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '🏪 Fornecedor',
                'verbose_name_plural': '🏪 Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Descrição dos itens comprados', max_length=200, verbose_name='📝 Descrição')),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total da compra', max_digits=10, verbose_name='💰 Valor Total')),
                ('data_compra', models.DateField(default=django.utils.timezone.now, verbose_name='📅 Data da Compra')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', '💵 Dinheiro'), ('pix', '📱 PIX'), ('debito', '💳 Débito'), ('credito', '🔄 Crédito')], default='dinheiro', max_length=10, verbose_name='💳 Forma de Pagamento')),
                ('parcelas', models.IntegerField(choices=[(1, '1x à vista'), (2, '2x sem juros'), (3, '3x sem juros'), (4, '4x sem juros'), (5, '5x sem juros'), (6, '6x sem juros'), (7, '7x sem juros'), (8, '8x sem juros'), (9, '9x sem juros'), (10, '10x sem juros'), (11, '11x sem juros'), (12, '12x sem juros')], default=1, help_text='Número de parcelas (apenas para crédito)', verbose_name='🔄 Parcelas')),
                ('observacoes', models.TextField(blank=True, help_text='Informações adicionais sobre a compra', verbose_name='📋 Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cartao_credito', models.ForeignKey(blank=True, help_text='Obrigatório apenas para pagamento no crédito', null=True, on_delete=django.db.models.deletion.PROTECT, to='compras.cartaocredito', verbose_name='💳 Cartão de Crédito')),
                ('fornecedor', models.ForeignKey(help_text='Selecione o fornecedor', on_delete=django.db.models.deletion.PROTECT, to='compras.fornecedor', verbose_name='🏪 Fornecedor')),
            ],
            options={
                'verbose_name': '🛒 Compra',
                'verbose_name_plural': '🛒 Compras',
                'ordering': ['-data_compra', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.IntegerField(verbose_name='Nº Parcela')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data Vencimento')),
                ('paga', models.BooleanField(default=False, verbose_name='Paga')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data Pagamento')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_detalhadas', to='compras.compra')),
            ],
            options={
                'verbose_name': '📅 Parcela',
                'verbose_name_plural': '📅 Parcelas',
                'ordering': ['compra', 'numero_parcela'],
                'unique_together': {('compra', 'numero_parcela')},
            },
        ),
    ]
